// Default Imports
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

// Page Imports
import { ThemeProvider } from "./components/theme-provider";
// Components
import Navbar from "./components/Navbar";

const defaultFont = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata = {
  title: "FRNZ | Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={defaultFont.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
